(el-get-bundle htmlize)
(el-get-bundle magit)
(el-get-bundle pallet)
(el-get-bundle popwin)
(el-get-bundle web-mode)
(el-get-bundle yasnippet)
(el-get-bundle helm)

;; cyberpunk theme (MELPA)
(el-get-bundle cyberpunk-theme)
